// Generated by scripts/generate-svgl-logos.mjs. See LICENSE and README.md.
export const svglCatalog: Record<string, { light: string; dark: string }> = {
  ossium: {
    light: "https://svgl.app/library/ossium_logo.svg",
    dark: "https://svgl.app/library/ossium_logo.svg",
  },
  plausibleanalytics: {
    light: "https://svgl.app/library/plausible.svg",
    dark: "https://svgl.app/library/plausible.svg",
  },
  ivyframework: {
    light: "https://svgl.app/library/ivy-framework.svg",
    dark: "https://svgl.app/library/ivy-framework.svg",
  },
  zaiaendless: {
    light: "https://svgl.app/library/zaia-endless.svg",
    dark: "https://svgl.app/library/zaia-endless.svg",
  },
  langchain: {
    light: "https://svgl.app/library/langchain-logo.svg",
    dark: "https://svgl.app/library/langchain-logo.svg",
  },
  granola: {
    light: "https://svgl.app/library/granola-light.svg",
    dark: "https://svgl.app/library/granola-dark.svg",
  },
  nvidia: {
    light: "https://svgl.app/library/nvidia-icon-light.svg",
    dark: "https://svgl.app/library/nvidia-icon-dark.svg",
  },
  protonmail: {
    light: "https://svgl.app/library/protonmail.svg",
    dark: "https://svgl.app/library/protonmail.svg",
  },
  protonvpn: {
    light: "https://svgl.app/library/protonvpn.svg",
    dark: "https://svgl.app/library/protonvpn.svg",
  },
  googleclassroom: {
    light: "https://svgl.app/library/google-classroom.svg",
    dark: "https://svgl.app/library/google-classroom.svg",
  },
  googleantigravity: {
    light: "https://svgl.app/library/antigravity.svg",
    dark: "https://svgl.app/library/antigravity.svg",
  },
  kimi: {
    light: "https://svgl.app/library/kimi-icon.svg",
    dark: "https://svgl.app/library/kimi-icon.svg",
  },
  zyft: {
    light: "https://svgl.app/library/zyft.svg",
    dark: "https://svgl.app/library/zyft.svg",
  },
  perspective: {
    light: "https://svgl.app/library/perspective-light.svg",
    dark: "https://svgl.app/library/perspective-dark.svg",
  },
  windsurf: {
    light: "https://svgl.app/library/windsurf-light.svg",
    dark: "https://svgl.app/library/windsurf-dark.svg",
  },
  mattermost: {
    light: "https://svgl.app/library/mattermost-light.svg",
    dark: "https://svgl.app/library/mattermost-dark.svg",
  },
  inngest: {
    light: "https://svgl.app/library/inngest-light.svg",
    dark: "https://svgl.app/library/inngest-dark.svg",
  },
  daisyui: {
    light: "https://svgl.app/library/daisyui.svg",
    dark: "https://svgl.app/library/daisyui.svg",
  },
  paypal: {
    light: "https://svgl.app/library/paypal.svg",
    dark: "https://svgl.app/library/paypal.svg",
  },
  googledrive: {
    light: "https://svgl.app/library/drive.svg",
    dark: "https://svgl.app/library/drive.svg",
  },
  amazonq: {
    light: "https://svgl.app/library/amazon-q.svg",
    dark: "https://svgl.app/library/amazon-q.svg",
  },
  mulesoft: {
    light: "https://svgl.app/library/mulesoft.svg",
    dark: "https://svgl.app/library/mulesoft.svg",
  },
  uv: {
    light: "https://svgl.app/library/uv.svg",
    dark: "https://svgl.app/library/uv.svg",
  },
  milanote: {
    light: "https://svgl.app/library/milanote-light.svg",
    dark: "https://svgl.app/library/milanote-dark.svg",
  },
  togetherai: {
    light: "https://svgl.app/library/togetherai_light.svg",
    dark: "https://svgl.app/library/togetherai_dark.svg",
  },
  suno: {
    light: "https://svgl.app/library/suno.svg",
    dark: "https://svgl.app/library/suno.svg",
  },
  groq: {
    light: "https://svgl.app/library/groq.svg",
    dark: "https://svgl.app/library/groq.svg",
  },
  cohere: {
    light: "https://svgl.app/library/cohere.svg",
    dark: "https://svgl.app/library/cohere.svg",
  },
  ollama: {
    light: "https://svgl.app/library/ollama_light.svg",
    dark: "https://svgl.app/library/ollama_dark.svg",
  },
  cisco: {
    light: "https://svgl.app/library/cisco_light.svg",
    dark: "https://svgl.app/library/cisco_dark.svg",
  },
  animate: {
    light: "https://svgl.app/library/animate.svg",
    dark: "https://svgl.app/library/animate.svg",
  },
  apolloio: {
    light: "https://svgl.app/library/apollo-io.svg",
    dark: "https://svgl.app/library/apollo-io.svg",
  },
  blender: {
    light: "https://svgl.app/library/blender.svg",
    dark: "https://svgl.app/library/blender.svg",
  },
  lua: {
    light: "https://svgl.app/library/lua.svg",
    dark: "https://svgl.app/library/lua.svg",
  },
  mercadolibre: {
    light: "https://svgl.app/library/mercado-libre.svg",
    dark: "https://svgl.app/library/mercado-libre.svg",
  },
  mercadopago: {
    light: "https://svgl.app/library/mercado-pago.svg",
    dark: "https://svgl.app/library/mercado-pago.svg",
  },
  basewell: {
    light: "https://svgl.app/library/basewell.svg",
    dark: "https://svgl.app/library/basewell.svg",
  },
  ahooks: {
    light: "https://svgl.app/library/ahooks.svg",
    dark: "https://svgl.app/library/ahooks.svg",
  },
  discord: {
    light: "https://svgl.app/library/discord.svg",
    dark: "https://svgl.app/library/discord.svg",
  },
  aliexpress: {
    light: "https://svgl.app/library/aliexpress-icon.svg",
    dark: "https://svgl.app/library/aliexpress-icon.svg",
  },
  preact: {
    light: "https://svgl.app/library/preact.svg",
    dark: "https://svgl.app/library/preact.svg",
  },
  react: {
    light: "https://svgl.app/library/react_light.svg",
    dark: "https://svgl.app/library/react_dark.svg",
  },
  svelte: {
    light: "https://svgl.app/library/svelte.svg",
    dark: "https://svgl.app/library/svelte.svg",
  },
  vue: {
    light: "https://svgl.app/library/vue.svg",
    dark: "https://svgl.app/library/vue.svg",
  },
  vuetify: {
    light: "https://svgl.app/library/vuetify.svg",
    dark: "https://svgl.app/library/vuetify.svg",
  },
  nuxt: {
    light: "https://svgl.app/library/nuxt.svg",
    dark: "https://svgl.app/library/nuxt.svg",
  },
  nuxtui: {
    light: "https://svgl.app/library/nuxt-ui-wordmark-light.svg",
    dark: "https://svgl.app/library/nuxt-ui-wordmark-dark.svg",
  },
  nuxtcontent: {
    light: "https://svgl.app/library/nuxt-content-wordmark-light.svg",
    dark: "https://svgl.app/library/nuxt-content-wordmark-dark.svg",
  },
  nuxtstudio: {
    light: "https://svgl.app/library/nuxt-studio-wordmark-light.svg",
    dark: "https://svgl.app/library/nuxt-studio-wordmark-dark.svg",
  },
  nuxthub: {
    light: "https://svgl.app/library/nuxthub.svg",
    dark: "https://svgl.app/library/nuxthub.svg",
  },
  docus: {
    light: "https://svgl.app/library/docus-light.svg",
    dark: "https://svgl.app/library/docus-dark.svg",
  },
  visualstudiocode: {
    light: "https://svgl.app/library/vscode.svg",
    dark: "https://svgl.app/library/vscode.svg",
  },
  ton: {
    light: "https://svgl.app/library/ton.svg",
    dark: "https://svgl.app/library/ton.svg",
  },
  locofy: {
    light: "https://svgl.app/library/locofy.svg",
    dark: "https://svgl.app/library/locofy.svg",
  },
  runway: {
    light: "https://svgl.app/library/runway.svg",
    dark: "https://svgl.app/library/runway.svg",
  },
  yarn: {
    light: "https://svgl.app/library/yarn.svg",
    dark: "https://svgl.app/library/yarn.svg",
  },
  jwt: {
    light: "https://svgl.app/library/jwt.svg",
    dark: "https://svgl.app/library/jwt.svg",
  },
  strapi: {
    light: "https://svgl.app/library/strapi.svg",
    dark: "https://svgl.app/library/strapi.svg",
  },
  figma: {
    light: "https://svgl.app/library/figma.svg",
    dark: "https://svgl.app/library/figma.svg",
  },
  spotify: {
    light: "https://svgl.app/library/spotify.svg",
    dark: "https://svgl.app/library/spotify.svg",
  },
  workos: {
    light: "https://svgl.app/library/workos.svg",
    dark: "https://svgl.app/library/workos-light.svg",
  },
  whop: {
    light: "https://svgl.app/library/whop.svg",
    dark: "https://svgl.app/library/whop-light.svg",
  },
  postman: {
    light: "https://svgl.app/library/postman.svg",
    dark: "https://svgl.app/library/postman.svg",
  },
  discordjs: {
    light: "https://svgl.app/library/djs.svg",
    dark: "https://svgl.app/library/djs.svg",
  },
  opensea: {
    light: "https://svgl.app/library/opensea.svg",
    dark: "https://svgl.app/library/opensea.svg",
  },
  algolia: {
    light: "https://svgl.app/library/algolia.svg",
    dark: "https://svgl.app/library/algolia.svg",
  },
  bootstrap: {
    light: "https://svgl.app/library/bootstrap.svg",
    dark: "https://svgl.app/library/bootstrap.svg",
  },
  facebook: {
    light: "https://svgl.app/library/facebook-icon.svg",
    dark: "https://svgl.app/library/facebook-icon.svg",
  },
  twitter: {
    light: "https://svgl.app/library/twitter.svg",
    dark: "https://svgl.app/library/twitter.svg",
  },
  esbuild: {
    light: "https://svgl.app/library/esbuild.svg",
    dark: "https://svgl.app/library/esbuild.svg",
  },
  deno: {
    light: "https://svgl.app/library/deno.svg",
    dark: "https://svgl.app/library/deno_dark.svg",
  },
  gatsby: {
    light: "https://svgl.app/library/gatsby.svg",
    dark: "https://svgl.app/library/gatsby.svg",
  },
  npm: {
    light: "https://svgl.app/library/npm.svg",
    dark: "https://svgl.app/library/npm.svg",
  },
  nuget: {
    light: "https://svgl.app/library/nuget.svg",
    dark: "https://svgl.app/library/nuget.svg",
  },
  homebrew: {
    light: "https://svgl.app/library/homebrew.svg",
    dark: "https://svgl.app/library/homebrew.svg",
  },
  sublimetext: {
    light: "https://svgl.app/library/sublimetext.svg",
    dark: "https://svgl.app/library/sublimetext.svg",
  },
  turborepo: {
    light: "https://svgl.app/library/turborepo-icon-light.svg",
    dark: "https://svgl.app/library/turborepo-icon-dark.svg",
  },
  tailwindcss: {
    light: "https://svgl.app/library/tailwindcss.svg",
    dark: "https://svgl.app/library/tailwindcss.svg",
  },
  wakatime: {
    light: "https://svgl.app/library/wakatime-dark.svg",
    dark: "https://svgl.app/library/wakatime-light.svg",
  },
  styledcomponents: {
    light: "https://svgl.app/library/styledcomponents.svg",
    dark: "https://svgl.app/library/styledcomponents.svg",
  },
  angular: {
    light: "https://svgl.app/library/angular.svg",
    dark: "https://svgl.app/library/angular.svg",
  },
  blitz: {
    light: "https://svgl.app/library/blitzjs.svg",
    dark: "https://svgl.app/library/blitzjs.svg",
  },
  lit: {
    light: "https://svgl.app/library/lit.svg",
    dark: "https://svgl.app/library/lit.svg",
  },
  atom: {
    light: "https://svgl.app/library/atom.svg",
    dark: "https://svgl.app/library/atom.svg",
  },
  youtube: {
    light: "https://svgl.app/library/youtube.svg",
    dark: "https://svgl.app/library/youtube.svg",
  },
  astro: {
    light: "https://svgl.app/library/astro-icon-light.svg",
    dark: "https://svgl.app/library/astro-icon-dark.svg",
  },
  google: {
    light: "https://svgl.app/library/google.svg",
    dark: "https://svgl.app/library/google.svg",
  },
  googleplay: {
    light: "https://svgl.app/library/googleplay.svg",
    dark: "https://svgl.app/library/googleplay.svg",
  },
  framer: {
    light: "https://svgl.app/library/framer.svg",
    dark: "https://svgl.app/library/framer_dark.svg",
  },
  netflix: {
    light: "https://svgl.app/library/netflix-icon.svg",
    dark: "https://svgl.app/library/netflix-icon.svg",
  },
  firefox: {
    light: "https://svgl.app/library/firefox.svg",
    dark: "https://svgl.app/library/firefox.svg",
  },
  linkedin: {
    light: "https://svgl.app/library/linkedin.svg",
    dark: "https://svgl.app/library/linkedin.svg",
  },
  telegram: {
    light: "https://svgl.app/library/telegram.svg",
    dark: "https://svgl.app/library/telegram.svg",
  },
  matrix: {
    light: "https://svgl.app/library/matrix-light.svg",
    dark: "https://svgl.app/library/matrix-dark.svg",
  },
  whatsapp: {
    light: "https://svgl.app/library/whatsapp-icon.svg",
    dark: "https://svgl.app/library/whatsapp-icon.svg",
  },
  headlessui: {
    light: "https://svgl.app/library/headlessui.svg",
    dark: "https://svgl.app/library/headlessui.svg",
  },
  kotlin: {
    light: "https://svgl.app/library/kotlin.svg",
    dark: "https://svgl.app/library/kotlin.svg",
  },
  storybook: {
    light: "https://svgl.app/library/storybook.svg",
    dark: "https://svgl.app/library/storybook.svg",
  },
  netlify: {
    light: "https://svgl.app/library/netlify.svg",
    dark: "https://svgl.app/library/netlify.svg",
  },
  solidjs: {
    light: "https://svgl.app/library/solidjs.svg",
    dark: "https://svgl.app/library/solidjs.svg",
  },
  mongodb: {
    light: "https://svgl.app/library/mongodb-icon-light.svg",
    dark: "https://svgl.app/library/mongodb-icon-dark.svg",
  },
  moon: {
    light: "https://svgl.app/library/moon.svg",
    dark: "https://svgl.app/library/moon.svg",
  },
  payloadcms: {
    light: "https://svgl.app/library/payload.svg",
    dark: "https://svgl.app/library/payload_dark.svg",
  },
  fly: {
    light: "https://svgl.app/library/fly.svg",
    dark: "https://svgl.app/library/fly.svg",
  },
  learnthis: {
    light: "https://svgl.app/library/learnthis.svg",
    dark: "https://svgl.app/library/learnthis.svg",
  },
  visualstudio: {
    light: "https://svgl.app/library/visual-studio.svg",
    dark: "https://svgl.app/library/visual-studio.svg",
  },
  chakraui: {
    light: "https://svgl.app/library/chakra-ui.svg",
    dark: "https://svgl.app/library/chakra-ui.svg",
  },
  expressjs: {
    light: "https://svgl.app/library/expressjs.svg",
    dark: "https://svgl.app/library/expressjs_dark.svg",
  },
  fastify: {
    light: "https://svgl.app/library/fastify.svg",
    dark: "https://svgl.app/library/fastify_dark.svg",
  },
  javascript: {
    light: "https://svgl.app/library/javascript.svg",
    dark: "https://svgl.app/library/javascript.svg",
  },
  jquery: {
    light: "https://svgl.app/library/jquery.svg",
    dark: "https://svgl.app/library/jquery_dark.svg",
  },
  rapidapi: {
    light: "https://svgl.app/library/rapidapi.svg",
    dark: "https://svgl.app/library/rapidapi.svg",
  },
  typescript: {
    light: "https://svgl.app/library/typescript.svg",
    dark: "https://svgl.app/library/typescript.svg",
  },
  bun: {
    light: "https://svgl.app/library/bun.svg",
    dark: "https://svgl.app/library/bun.svg",
  },
  buildship: {
    light: "https://svgl.app/library/buildship.svg",
    dark: "https://svgl.app/library/buildship.svg",
  },
  twilio: {
    light: "https://svgl.app/library/twilio.svg",
    dark: "https://svgl.app/library/twilio.svg",
  },
  arc: {
    light: "https://svgl.app/library/arc_browser.svg",
    dark: "https://svgl.app/library/arc_browser.svg",
  },
  qwik: {
    light: "https://svgl.app/library/qwik.svg",
    dark: "https://svgl.app/library/qwik.svg",
  },
  coinbase: {
    light: "https://svgl.app/library/coinbase.svg",
    dark: "https://svgl.app/library/coinbase.svg",
  },
  authy: {
    light: "https://svgl.app/library/authy.svg",
    dark: "https://svgl.app/library/authy.svg",
  },
  nestjs: {
    light: "https://svgl.app/library/nestjs.svg",
    dark: "https://svgl.app/library/nestjs.svg",
  },
  githubcopilot: {
    light: "https://svgl.app/library/copilot.svg",
    dark: "https://svgl.app/library/copilot_dark.svg",
  },
  railway: {
    light: "https://svgl.app/library/railway.svg",
    dark: "https://svgl.app/library/railway_dark.svg",
  },
  docusaurus: {
    light: "https://svgl.app/library/docusaurus.svg",
    dark: "https://svgl.app/library/docusaurus.svg",
  },
  twitch: {
    light: "https://svgl.app/library/twitch.svg",
    dark: "https://svgl.app/library/twitch.svg",
  },
  godaddy: {
    light: "https://svgl.app/library/godaddy.svg",
    dark: "https://svgl.app/library/godaddy_dark.svg",
  },
  udemy: {
    light: "https://svgl.app/library/udemy.svg",
    dark: "https://svgl.app/library/udemy_dark.svg",
  },
  graphql: {
    light: "https://svgl.app/library/graphql.svg",
    dark: "https://svgl.app/library/graphql.svg",
  },
  grok: {
    light: "https://svgl.app/library/grok-light.svg",
    dark: "https://svgl.app/library/grok-dark.svg",
  },
  gitlab: {
    light: "https://svgl.app/library/gitlab.svg",
    dark: "https://svgl.app/library/gitlab.svg",
  },
  prisma: {
    light: "https://svgl.app/library/prisma.svg",
    dark: "https://svgl.app/library/prisma_dark.svg",
  },
  go: {
    light: "https://svgl.app/library/golang.svg",
    dark: "https://svgl.app/library/golang_dark.svg",
  },
  platzi: {
    light: "https://svgl.app/library/platzi.svg",
    dark: "https://svgl.app/library/platzi.svg",
  },
  coursera: {
    light: "https://svgl.app/library/coursera.svg",
    dark: "https://svgl.app/library/coursera.svg",
  },
  udacity: {
    light: "https://svgl.app/library/udacity.svg",
    dark: "https://svgl.app/library/udacity.svg",
  },
  kubernetes: {
    light: "https://svgl.app/library/kubernetes.svg",
    dark: "https://svgl.app/library/kubernetes.svg",
  },
  docker: {
    light: "https://svgl.app/library/docker.svg",
    dark: "https://svgl.app/library/docker.svg",
  },
  amazonwebservices: {
    light: "https://svgl.app/library/aws_light.svg",
    dark: "https://svgl.app/library/aws_dark.svg",
  },
  microsoftazure: {
    light: "https://svgl.app/library/azure.svg",
    dark: "https://svgl.app/library/azure.svg",
  },
  microsoftaccess: {
    light: "https://svgl.app/library/microsoft-access.svg",
    dark: "https://svgl.app/library/microsoft-access.svg",
  },
  microsoftclipchamp: {
    light: "https://svgl.app/library/microsoft-clipchamp.svg",
    dark: "https://svgl.app/library/microsoft-clipchamp.svg",
  },
  microsoftcopilot: {
    light: "https://svgl.app/library/microsoft-copilot.svg",
    dark: "https://svgl.app/library/microsoft-copilot.svg",
  },
  microsoftdefender: {
    light: "https://svgl.app/library/microsoft-defender.svg",
    dark: "https://svgl.app/library/microsoft-defender.svg",
  },
  microsoftdesigner: {
    light: "https://svgl.app/library/microsoft-designer.svg",
    dark: "https://svgl.app/library/microsoft-designer.svg",
  },
  microsofteditor: {
    light: "https://svgl.app/library/microsoft-editor.svg",
    dark: "https://svgl.app/library/microsoft-editor.svg",
  },
  microsoftexcel: {
    light: "https://svgl.app/library/microsoft-excel.svg",
    dark: "https://svgl.app/library/microsoft-excel.svg",
  },
  microsoftonedrive: {
    light: "https://svgl.app/library/microsoft-onedrive.svg",
    dark: "https://svgl.app/library/microsoft-onedrive.svg",
  },
  microsoftonenote: {
    light: "https://svgl.app/library/microsoft-onenote.svg",
    dark: "https://svgl.app/library/microsoft-onenote.svg",
  },
  microsoftpowerpoint: {
    light: "https://svgl.app/library/microsoft-powerpoint.svg",
    dark: "https://svgl.app/library/microsoft-powerpoint.svg",
  },
  microsoftsharepoint: {
    light: "https://svgl.app/library/microsoft-sharepoint.svg",
    dark: "https://svgl.app/library/microsoft-sharepoint.svg",
  },
  microsoftteams: {
    light: "https://svgl.app/library/microsoft-teams.svg",
    dark: "https://svgl.app/library/microsoft-teams.svg",
  },
  microsoftword: {
    light: "https://svgl.app/library/microsoft-word.svg",
    dark: "https://svgl.app/library/microsoft-word.svg",
  },
  heroku: {
    light: "https://svgl.app/library/heroku.svg",
    dark: "https://svgl.app/library/heroku.svg",
  },
  jetbrains: {
    light: "https://svgl.app/library/jetbrainsSolid.svg",
    dark: "https://svgl.app/library/jetbrainsSolid.svg",
  },
  jetbrainsrider: {
    light: "https://svgl.app/library/rider.svg",
    dark: "https://svgl.app/library/rider.svg",
  },
  planetscale: {
    light: "https://svgl.app/library/planetscale.svg",
    dark: "https://svgl.app/library/planetscale_dark.svg",
  },
  playwright: {
    light: "https://svgl.app/library/playwright.svg",
    dark: "https://svgl.app/library/playwright.svg",
  },
  atlassian: {
    light: "https://svgl.app/library/atlassian.svg",
    dark: "https://svgl.app/library/atlassian.svg",
  },
  discourse: {
    light: "https://svgl.app/library/discourse.svg",
    dark: "https://svgl.app/library/discourse.svg",
  },
  ember: {
    light: "https://svgl.app/library/ember.svg",
    dark: "https://svgl.app/library/ember.svg",
  },
  expo: {
    light: "https://svgl.app/library/expo.svg",
    dark: "https://svgl.app/library/expo.svg",
  },
  flutter: {
    light: "https://svgl.app/library/flutter.svg",
    dark: "https://svgl.app/library/flutter.svg",
  },
  auth0: {
    light: "https://svgl.app/library/auth0.svg",
    dark: "https://svgl.app/library/auth0.svg",
  },
  authjs: {
    light: "https://svgl.app/library/authjs.svg",
    dark: "https://svgl.app/library/authjs.svg",
  },
  fresh: {
    light: "https://svgl.app/library/fresh.svg",
    dark: "https://svgl.app/library/fresh.svg",
  },
  git: {
    light: "https://svgl.app/library/git.svg",
    dark: "https://svgl.app/library/git.svg",
  },
  hostgator: {
    light: "https://svgl.app/library/hostgator.svg",
    dark: "https://svgl.app/library/hostgator.svg",
  },
  intellijidea: {
    light: "https://svgl.app/library/intellijidea.svg",
    dark: "https://svgl.app/library/intellijidea.svg",
  },
  jasmine: {
    light: "https://svgl.app/library/jasmine.svg",
    dark: "https://svgl.app/library/jasmine.svg",
  },
  java: {
    light: "https://svgl.app/library/java.svg",
    dark: "https://svgl.app/library/java.svg",
  },
  jest: {
    light: "https://svgl.app/library/jest.svg",
    dark: "https://svgl.app/library/jest.svg",
  },
  krakenjs: {
    light: "https://svgl.app/library/krakenjs.svg",
    dark: "https://svgl.app/library/krakenjs.svg",
  },
  laravel: {
    light: "https://svgl.app/library/laravel.svg",
    dark: "https://svgl.app/library/laravel.svg",
  },
  mariadb: {
    light: "https://svgl.app/library/mariadb.svg",
    dark: "https://svgl.app/library/mariadb.svg",
  },
  materialui: {
    light: "https://svgl.app/library/materialui.svg",
    dark: "https://svgl.app/library/materialui.svg",
  },
  mysql: {
    light: "https://svgl.app/library/mysql-icon-light.svg",
    dark: "https://svgl.app/library/mysql-icon-dark.svg",
  },
  parcel: {
    light: "https://svgl.app/library/parcel.svg",
    dark: "https://svgl.app/library/parcel.svg",
  },
  pm2: {
    light: "https://svgl.app/library/pm2.svg",
    dark: "https://svgl.app/library/pm2.svg",
  },
  postgresql: {
    light: "https://svgl.app/library/postgresql.svg",
    dark: "https://svgl.app/library/postgresql.svg",
  },
  reactquery: {
    light: "https://svgl.app/library/reactquery.svg",
    dark: "https://svgl.app/library/reactquery.svg",
  },
  devto: {
    light: "https://svgl.app/library/devto-light.svg",
    dark: "https://svgl.app/library/devto-dark.svg",
  },
  redis: {
    light: "https://svgl.app/library/redis.svg",
    dark: "https://svgl.app/library/redis.svg",
  },
  redwoodjs: {
    light: "https://svgl.app/library/redwoodjs.svg",
    dark: "https://svgl.app/library/redwoodjs.svg",
  },
  ruby: {
    light: "https://svgl.app/library/ruby.svg",
    dark: "https://svgl.app/library/ruby.svg",
  },
  scala: {
    light: "https://svgl.app/library/scala.svg",
    dark: "https://svgl.app/library/scala.svg",
  },
  sequelize: {
    light: "https://svgl.app/library/sequelize.svg",
    dark: "https://svgl.app/library/sequelize.svg",
  },
  spinnaker: {
    light: "https://svgl.app/library/spinnaker.svg",
    dark: "https://svgl.app/library/spinnaker.svg",
  },
  sqlite: {
    light: "https://svgl.app/library/sqlite.svg",
    dark: "https://svgl.app/library/sqlite.svg",
  },
  swagger: {
    light: "https://svgl.app/library/swagger.svg",
    dark: "https://svgl.app/library/swagger.svg",
  },
  swift: {
    light: "https://svgl.app/library/swift.svg",
    dark: "https://svgl.app/library/swift.svg",
  },
  typeorm: {
    light: "https://svgl.app/library/typeorm.svg",
    dark: "https://svgl.app/library/typeorm.svg",
  },
  unity: {
    light: "https://svgl.app/library/unity.svg",
    dark: "https://svgl.app/library/unity_dark.svg",
  },
  vim: {
    light: "https://svgl.app/library/vim.svg",
    dark: "https://svgl.app/library/vim.svg",
  },
  pocketbase: {
    light: "https://svgl.app/library/pocket-base.svg",
    dark: "https://svgl.app/library/pocket-base.svg",
  },
  openbootcamp: {
    light: "https://svgl.app/library/openbootcamp.svg",
    dark: "https://svgl.app/library/openbootcamp.svg",
  },
  digitalocean: {
    light: "https://svgl.app/library/digitalocean.svg",
    dark: "https://svgl.app/library/digitalocean.svg",
  },
  disney: {
    light: "https://svgl.app/library/disneyplus.svg",
    dark: "https://svgl.app/library/disneyplus.svg",
  },
  reactrouter: {
    light: "https://svgl.app/library/reactrouter.svg",
    dark: "https://svgl.app/library/reactrouter.svg",
  },
  amp: {
    light: "https://svgl.app/library/amp.svg",
    dark: "https://svgl.app/library/amp.svg",
  },
  developerstudentclub: {
    light: "https://svgl.app/library/gdsc.svg",
    dark: "https://svgl.app/library/gdsc.svg",
  },
  bravebrowser: {
    light: "https://svgl.app/library/brave.svg",
    dark: "https://svgl.app/library/brave.svg",
  },
  eclipseide: {
    light: "https://svgl.app/library/eclipse.svg",
    dark: "https://svgl.app/library/eclipse.svg",
  },
  threejs: {
    light: "https://svgl.app/library/threejs-light.svg",
    dark: "https://svgl.app/library/threejs-dark.svg",
  },
  html5: {
    light: "https://svgl.app/library/html5.svg",
    dark: "https://svgl.app/library/html5.svg",
  },
  cssnew: {
    light: "https://svgl.app/library/css.svg",
    dark: "https://svgl.app/library/css.svg",
  },
  css: {
    light: "https://svgl.app/library/css_old.svg",
    dark: "https://svgl.app/library/css_old.svg",
  },
  midudev: {
    light: "https://svgl.app/library/midudev.svg",
    dark: "https://svgl.app/library/midudev.svg",
  },
  apple: {
    light: "https://svgl.app/library/apple.svg",
    dark: "https://svgl.app/library/apple_dark.svg",
  },
  appstore: {
    light: "https://svgl.app/library/appstore.svg",
    dark: "https://svgl.app/library/appstore.svg",
  },
  windows: {
    light: "https://svgl.app/library/windows.svg",
    dark: "https://svgl.app/library/windows.svg",
  },
  python: {
    light: "https://svgl.app/library/python.svg",
    dark: "https://svgl.app/library/python.svg",
  },
  solidity: {
    light: "https://svgl.app/library/solidity.svg",
    dark: "https://svgl.app/library/solidity.svg",
  },
  turbopack: {
    light: "https://svgl.app/library/turbopack-icon-light.svg",
    dark: "https://svgl.app/library/turbopack-icon-dark.svg",
  },
  builder: {
    light: "https://svgl.app/library/builder.svg",
    dark: "https://svgl.app/library/builder.svg",
  },
  babel: {
    light: "https://svgl.app/library/babel.svg",
    dark: "https://svgl.app/library/babel.svg",
  },
  surrealdb: {
    light: "https://svgl.app/library/surrealdb.svg",
    dark: "https://svgl.app/library/surrealdb.svg",
  },
  jetbrainsspace: {
    light: "https://svgl.app/library/jetbrains-space.svg",
    dark: "https://svgl.app/library/jetbrains-space.svg",
  },
  stimulus: {
    light: "https://svgl.app/library/stimulus.svg",
    dark: "https://svgl.app/library/stimulus.svg",
  },
  windicss: {
    light: "https://svgl.app/library/windicss.svg",
    dark: "https://svgl.app/library/windicss.svg",
  },
  mastodon: {
    light: "https://svgl.app/library/mastodon.svg",
    dark: "https://svgl.app/library/mastodon.svg",
  },
  upstash: {
    light: "https://svgl.app/library/upstash.svg",
    dark: "https://svgl.app/library/upstash.svg",
  },
  storyblok: {
    light: "https://svgl.app/library/storyblok.svg",
    dark: "https://svgl.app/library/storyblok.svg",
  },
  cloudflareworkers: {
    light: "https://svgl.app/library/cloudflare-workers.svg",
    dark: "https://svgl.app/library/cloudflare-workers.svg",
  },
  cloudflare: {
    light: "https://svgl.app/library/cloudflare.svg",
    dark: "https://svgl.app/library/cloudflare.svg",
  },
  bing: {
    light: "https://svgl.app/library/bing.svg",
    dark: "https://svgl.app/library/bing.svg",
  },
  cloudinary: {
    light: "https://svgl.app/library/cloudinary.svg",
    dark: "https://svgl.app/library/cloudinary.svg",
  },
  dart: {
    light: "https://svgl.app/library/dart.svg",
    dark: "https://svgl.app/library/dart.svg",
  },
  hcaptcha: {
    light: "https://svgl.app/library/hcaptcha.svg",
    dark: "https://svgl.app/library/hcaptcha.svg",
  },
  appwrite: {
    light: "https://svgl.app/library/appwrite.svg",
    dark: "https://svgl.app/library/appwrite.svg",
  },
  loom: {
    light: "https://svgl.app/library/loom.svg",
    dark: "https://svgl.app/library/loom.svg",
  },
  hulu: {
    light: "https://svgl.app/library/hulu.svg",
    dark: "https://svgl.app/library/hulu-dark.svg",
  },
  stackblitz: {
    light: "https://svgl.app/library/stackblitz.svg",
    dark: "https://svgl.app/library/stackblitz.svg",
  },
  binance: {
    light: "https://svgl.app/library/binance.svg",
    dark: "https://svgl.app/library/binance.svg",
  },
  messenger: {
    light: "https://svgl.app/library/messenger.svg",
    dark: "https://svgl.app/library/messenger.svg",
  },
  nhost: {
    light: "https://svgl.app/library/nhost.svg",
    dark: "https://svgl.app/library/nhost.svg",
  },
  medusa: {
    light: "https://svgl.app/library/medusa.svg",
    dark: "https://svgl.app/library/medusa.svg",
  },
  wordpress: {
    light: "https://svgl.app/library/wordpress.svg",
    dark: "https://svgl.app/library/wordpress.svg",
  },
  microsoft: {
    light: "https://svgl.app/library/microsoft.svg",
    dark: "https://svgl.app/library/microsoft.svg",
  },
  elementor: {
    light: "https://svgl.app/library/elementor.svg",
    dark: "https://svgl.app/library/elementor.svg",
  },
  kick: {
    light: "https://svgl.app/library/kick-light.svg",
    dark: "https://svgl.app/library/kick-dark.svg",
  },
  primevideo: {
    light: "https://svgl.app/library/prime-video.svg",
    dark: "https://svgl.app/library/prime-video.svg",
  },
  chrome: {
    light: "https://svgl.app/library/chrome.svg",
    dark: "https://svgl.app/library/chrome.svg",
  },
  rxjs: {
    light: "https://svgl.app/library/rxjs.svg",
    dark: "https://svgl.app/library/rxjs.svg",
  },
  electron: {
    light: "https://svgl.app/library/electron.svg",
    dark: "https://svgl.app/library/electron.svg",
  },
  redux: {
    light: "https://svgl.app/library/redux.svg",
    dark: "https://svgl.app/library/redux.svg",
  },
  trustwallet: {
    light: "https://svgl.app/library/trust.svg",
    dark: "https://svgl.app/library/trust.svg",
  },
  php: {
    light: "https://svgl.app/library/php.svg",
    dark: "https://svgl.app/library/php_dark.svg",
  },
  hugo: {
    light: "https://svgl.app/library/hugo.svg",
    dark: "https://svgl.app/library/hugo.svg",
  },
  sass: {
    light: "https://svgl.app/library/sass.svg",
    dark: "https://svgl.app/library/sass.svg",
  },
  pinia: {
    light: "https://svgl.app/library/pinia.svg",
    dark: "https://svgl.app/library/pinia.svg",
  },
  neon: {
    light: "https://svgl.app/library/neon.svg",
    dark: "https://svgl.app/library/neon.svg",
  },
  infojobs: {
    light: "https://svgl.app/library/infojobs-logo.svg",
    dark: "https://svgl.app/library/infojobs-logo.svg",
  },
  linear: {
    light: "https://svgl.app/library/linear.svg",
    dark: "https://svgl.app/library/linear.svg",
  },
  tor: {
    light: "https://svgl.app/library/tor.svg",
    dark: "https://svgl.app/library/tor.svg",
  },
  codesandbox: {
    light: "https://svgl.app/library/codesandbox-square.svg",
    dark: "https://svgl.app/library/codesandbox-square.svg",
  },
  skype: {
    light: "https://svgl.app/library/skype.svg",
    dark: "https://svgl.app/library/skype.svg",
  },
  tauri: {
    light: "https://svgl.app/library/tauri.svg",
    dark: "https://svgl.app/library/tauri.svg",
  },
  webkit: {
    light: "https://svgl.app/library/webkit.svg",
    dark: "https://svgl.app/library/webkit.svg",
  },
  duckduckgo: {
    light: "https://svgl.app/library/duckduckgo.svg",
    dark: "https://svgl.app/library/duckduckgo.svg",
  },
  obsidian: {
    light: "https://svgl.app/library/obsidian.svg",
    dark: "https://svgl.app/library/obsidian.svg",
  },
  zod: {
    light: "https://svgl.app/library/zod.svg",
    dark: "https://svgl.app/library/zod.svg",
  },
  valibot: {
    light: "https://svgl.app/library/valibot.svg",
    dark: "https://svgl.app/library/valibot.svg",
  },
  dreamweaver: {
    light: "https://svgl.app/library/dw.svg",
    dark: "https://svgl.app/library/dw.svg",
  },
  openai: {
    light: "https://svgl.app/library/openai.svg",
    dark: "https://svgl.app/library/openai_dark.svg",
  },
  threads: {
    light: "https://svgl.app/library/threads.svg",
    dark: "https://svgl.app/library/threads_dark.svg",
  },
  instagram: {
    light: "https://svgl.app/library/instagram-icon.svg",
    dark: "https://svgl.app/library/instagram-icon.svg",
  },
  vueuse: {
    light: "https://svgl.app/library/vueuse.svg",
    dark: "https://svgl.app/library/vueuse.svg",
  },
  microsoftsqlserver: {
    light: "https://svgl.app/library/sql-server.svg",
    dark: "https://svgl.app/library/sql-server.svg",
  },
  hono: {
    light: "https://svgl.app/library/hono.svg",
    dark: "https://svgl.app/library/hono.svg",
  },
  million: {
    light: "https://svgl.app/library/million.svg",
    dark: "https://svgl.app/library/million.svg",
  },
  pandacss: {
    light: "https://svgl.app/library/pandacss.svg",
    dark: "https://svgl.app/library/pandacss.svg",
  },
  pulumi: {
    light: "https://svgl.app/library/pulumi.svg",
    dark: "https://svgl.app/library/pulumi.svg",
  },
  fastapi: {
    light: "https://svgl.app/library/fastapi.svg",
    dark: "https://svgl.app/library/fastapi.svg",
  },
  codium: {
    light: "https://svgl.app/library/codium.svg",
    dark: "https://svgl.app/library/codium.svg",
  },
  crossplane: {
    light: "https://svgl.app/library/crossplane.svg",
    dark: "https://svgl.app/library/crossplane.svg",
  },
  volta: {
    light: "https://svgl.app/library/volta-dark.svg",
    dark: "https://svgl.app/library/volta-light.svg",
  },
  typesense: {
    light: "https://svgl.app/library/typesense.svg",
    dark: "https://svgl.app/library/typesense.svg",
  },
  bitcoin: {
    light: "https://svgl.app/library/btc.svg",
    dark: "https://svgl.app/library/btc.svg",
  },
  ethereum: {
    light: "https://svgl.app/library/eth.svg",
    dark: "https://svgl.app/library/eth.svg",
  },
  solana: {
    light: "https://svgl.app/library/sol.svg",
    dark: "https://svgl.app/library/sol.svg",
  },
  dogecoin: {
    light: "https://svgl.app/library/doge.svg",
    dark: "https://svgl.app/library/doge.svg",
  },
  xrp: {
    light: "https://svgl.app/library/xrp.svg",
    dark: "https://svgl.app/library/xrp.svg",
  },
  bnb: {
    light: "https://svgl.app/library/bnb.svg",
    dark: "https://svgl.app/library/bnb.svg",
  },
  link: {
    light: "https://svgl.app/library/link.svg",
    dark: "https://svgl.app/library/link.svg",
  },
  polygon: {
    light: "https://svgl.app/library/matic.svg",
    dark: "https://svgl.app/library/matic.svg",
  },
  algorand: {
    light: "https://svgl.app/library/algorand.svg",
    dark: "https://svgl.app/library/algorand.svg",
  },
  tether: {
    light: "https://svgl.app/library/tether.svg",
    dark: "https://svgl.app/library/tether.svg",
  },
  xformerlytwitter: {
    light: "https://svgl.app/library/x.svg",
    dark: "https://svgl.app/library/x_dark.svg",
  },
  adobe: {
    light: "https://svgl.app/library/adobe.svg",
    dark: "https://svgl.app/library/adobe.svg",
  },
  aftereffects: {
    light: "https://svgl.app/library/after-effects.svg",
    dark: "https://svgl.app/library/after-effects.svg",
  },
  canva: {
    light: "https://svgl.app/library/canva.svg",
    dark: "https://svgl.app/library/canva.svg",
  },
  illustrator: {
    light: "https://svgl.app/library/ai_appicon_64_grayscale.svg",
    dark: "https://svgl.app/library/ai_appicon_64_grayscale.svg",
  },
  indesign: {
    light: "https://svgl.app/library/indesign.svg",
    dark: "https://svgl.app/library/indesign.svg",
  },
  lightroom: {
    light: "https://svgl.app/library/lightroom.svg",
    dark: "https://svgl.app/library/lightroom.svg",
  },
  photoshop: {
    light: "https://svgl.app/library/ps_appicon_64_grayscale.svg",
    dark: "https://svgl.app/library/ps_appicon_64_grayscale.svg",
  },
  premiere: {
    light: "https://svgl.app/library/premiere.svg",
    dark: "https://svgl.app/library/premiere.svg",
  },
  vk: {
    light: "https://svgl.app/library/vk.svg",
    dark: "https://svgl.app/library/vk.svg",
  },
  hoppscotch: {
    light: "https://svgl.app/library/hoppscotch.svg",
    dark: "https://svgl.app/library/hoppscotch.svg",
  },
  opera: {
    light: "https://svgl.app/library/opera.svg",
    dark: "https://svgl.app/library/opera.svg",
  },
  salesforce: {
    light: "https://svgl.app/library/salesforce.svg",
    dark: "https://svgl.app/library/salesforce.svg",
  },
  unrealengine: {
    light: "https://svgl.app/library/unreal_engine.svg",
    dark: "https://svgl.app/library/unreal_engine_dark.svg",
  },
  godotengine: {
    light: "https://svgl.app/library/godot_engine.svg",
    dark: "https://svgl.app/library/godot_engine.svg",
  },
  datadog: {
    light: "https://svgl.app/library/datadog.svg",
    dark: "https://svgl.app/library/datadog.svg",
  },
  tron: {
    light: "https://svgl.app/library/tron.svg",
    dark: "https://svgl.app/library/tron.svg",
  },
  randevum: {
    light: "https://svgl.app/library/randevum.svg",
    dark: "https://svgl.app/library/randevum.svg",
  },
  chromium: {
    light: "https://svgl.app/library/chromium.svg",
    dark: "https://svgl.app/library/chromium.svg",
  },
  edge: {
    light: "https://svgl.app/library/edge.svg",
    dark: "https://svgl.app/library/edge.svg",
  },
  safari: {
    light: "https://svgl.app/library/safari.svg",
    dark: "https://svgl.app/library/safari.svg",
  },
  vivaldi: {
    light: "https://svgl.app/library/vivaldi.svg",
    dark: "https://svgl.app/library/vivaldi.svg",
  },
  beacon: {
    light: "https://svgl.app/library/Beacon-Logo.svg",
    dark: "https://svgl.app/library/Beacon-Logo.svg",
  },
  affinitydesigner: {
    light: "https://svgl.app/library/affinity_designer.svg",
    dark: "https://svgl.app/library/affinity_designer.svg",
  },
  affinityphoto: {
    light: "https://svgl.app/library/affinity_photo.svg",
    dark: "https://svgl.app/library/affinity_photo.svg",
  },
  affinitypublisher: {
    light: "https://svgl.app/library/affinity_publisher.svg",
    dark: "https://svgl.app/library/affinity_publisher.svg",
  },
  roblox: {
    light: "https://svgl.app/library/roblox_light.svg",
    dark: "https://svgl.app/library/roblox.svg",
  },
  statelyai: {
    light: "https://svgl.app/library/stately.svg",
    dark: "https://svgl.app/library/stately_dark.svg",
  },
  xstate: {
    light: "https://svgl.app/library/xstate.svg",
    dark: "https://svgl.app/library/xstate_dark.svg",
  },
  hashnode: {
    light: "https://svgl.app/library/hashnode.svg",
    dark: "https://svgl.app/library/hashnode.svg",
  },
  rowy: {
    light: "https://svgl.app/library/rowy.svg",
    dark: "https://svgl.app/library/rowy.svg",
  },
  calcom: {
    light: "https://svgl.app/library/cal.svg",
    dark: "https://svgl.app/library/cal_dark.svg",
  },
  calendly: {
    light: "https://svgl.app/library/calendly.svg",
    dark: "https://svgl.app/library/calendly.svg",
  },
  patreon: {
    light: "https://svgl.app/library/patreon.svg",
    dark: "https://svgl.app/library/patreon_dark.svg",
  },
  peerlist: {
    light: "https://svgl.app/library/peerlist.svg",
    dark: "https://svgl.app/library/peerlist.svg",
  },
  producthunt: {
    light: "https://svgl.app/library/producthunt.svg",
    dark: "https://svgl.app/library/producthunt.svg",
  },
  remotion: {
    light: "https://svgl.app/library/remotion.svg",
    dark: "https://svgl.app/library/remotion.svg",
  },
  warp: {
    light: "https://svgl.app/library/warp.svg",
    dark: "https://svgl.app/library/warp.svg",
  },
  sst: {
    light: "https://svgl.app/library/sst.svg",
    dark: "https://svgl.app/library/sst.svg",
  },
  documenso: {
    light: "https://svgl.app/library/documenso.svg",
    dark: "https://svgl.app/library/documenso_dark.svg",
  },
  bash: {
    light: "https://svgl.app/library/bash.svg",
    dark: "https://svgl.app/library/bash_dark.svg",
  },
  c: {
    light: "https://svgl.app/library/csharp.svg",
    dark: "https://svgl.app/library/csharp.svg",
  },
  cobol: {
    light: "https://svgl.app/library/cobol.svg",
    dark: "https://svgl.app/library/cobol.svg",
  },
  fortran: {
    light: "https://svgl.app/library/fortran.svg",
    dark: "https://svgl.app/library/fortran.svg",
  },
  haskell: {
    light: "https://svgl.app/library/haskell.svg",
    dark: "https://svgl.app/library/haskell.svg",
  },
  matlab: {
    light: "https://svgl.app/library/matlab.svg",
    dark: "https://svgl.app/library/matlab.svg",
  },
  r: {
    light: "https://svgl.app/library/r.svg",
    dark: "https://svgl.app/library/r_dark.svg",
  },
  rust: {
    light: "https://svgl.app/library/rust.svg",
    dark: "https://svgl.app/library/rust_dark.svg",
  },
  zig: {
    light: "https://svgl.app/library/zig.svg",
    dark: "https://svgl.app/library/zig.svg",
  },
  instatus: {
    light: "https://svgl.app/library/instatus.svg",
    dark: "https://svgl.app/library/instatus_dark.svg",
  },
  front: {
    light: "https://svgl.app/library/front.svg",
    dark: "https://svgl.app/library/front.svg",
  },
  monero: {
    light: "https://svgl.app/library/monero.svg",
    dark: "https://svgl.app/library/monero.svg",
  },
  axiom: {
    light: "https://svgl.app/library/axiom-light.svg",
    dark: "https://svgl.app/library/axiom-dark.svg",
  },
  django: {
    light: "https://svgl.app/library/django.svg",
    dark: "https://svgl.app/library/django.svg",
  },
  zeabur: {
    light: "https://svgl.app/library/zeabur-light.svg",
    dark: "https://svgl.app/library/zeabur-dark.svg",
  },
  metamask: {
    light: "https://svgl.app/library/metamask.svg",
    dark: "https://svgl.app/library/metamask.svg",
  },
  shadcnui: {
    light: "https://svgl.app/library/shadcn-ui.svg",
    dark: "https://svgl.app/library/shadcn-ui_dark.svg",
  },
  putio: {
    light: "https://svgl.app/library/putio.svg",
    dark: "https://svgl.app/library/putio.svg",
  },
  pinterest: {
    light: "https://svgl.app/library/pinterest.svg",
    dark: "https://svgl.app/library/pinterest.svg",
  },
  reflex: {
    light: "https://svgl.app/library/reflex-dark.svg",
    dark: "https://svgl.app/library/reflex-light.svg",
  },
  linux: {
    light: "https://svgl.app/library/linux.svg",
    dark: "https://svgl.app/library/linux.svg",
  },
  xd: {
    light: "https://svgl.app/library/adobe-xd.svg",
    dark: "https://svgl.app/library/adobe-xd.svg",
  },
  axure: {
    light: "https://svgl.app/library/axure.svg",
    dark: "https://svgl.app/library/axure.svg",
  },
  penpot: {
    light: "https://svgl.app/library/penpot.svg",
    dark: "https://svgl.app/library/penpot_dark.svg",
  },
  sketch: {
    light: "https://svgl.app/library/sketch_light.svg",
    dark: "https://svgl.app/library/sketch.svg",
  },
  gimp: {
    light: "https://svgl.app/library/gimp.svg",
    dark: "https://svgl.app/library/gimp.svg",
  },
  ubuntu: {
    light: "https://svgl.app/library/ubuntu.svg",
    dark: "https://svgl.app/library/ubuntu.svg",
  },
  cypress: {
    light: "https://svgl.app/library/cypress.svg",
    dark: "https://svgl.app/library/cypress.svg",
  },
  reddit: {
    light: "https://svgl.app/library/reddit.svg",
    dark: "https://svgl.app/library/reddit.svg",
  },
  jetbrainswebstorm: {
    light: "https://svgl.app/library/webstorm.svg",
    dark: "https://svgl.app/library/webstorm.svg",
  },
  jetbrainspycharm: {
    light: "https://svgl.app/library/pycharm.svg",
    dark: "https://svgl.app/library/pycharm.svg",
  },
  jetbrainsfleet: {
    light: "https://svgl.app/library/fleet.svg",
    dark: "https://svgl.app/library/fleet.svg",
  },
  jetbrainsrubymine: {
    light: "https://svgl.app/library/rubymine.svg",
    dark: "https://svgl.app/library/rubymine.svg",
  },
  jetbrainsphpstorm: {
    light: "https://svgl.app/library/phpstorm.svg",
    dark: "https://svgl.app/library/phpstorm.svg",
  },
  monkeytype: {
    light: "https://svgl.app/library/monkeytype.svg",
    dark: "https://svgl.app/library/monkeytype.svg",
  },
  pycharm: {
    light: "https://svgl.app/library/pycharm.svg",
    dark: "https://svgl.app/library/pycharm.svg",
  },
  shopify: {
    light: "https://svgl.app/library/shopify.svg",
    dark: "https://svgl.app/library/shopify.svg",
  },
  webflow: {
    light: "https://svgl.app/library/webflow.svg",
    dark: "https://svgl.app/library/webflow.svg",
  },
  sky: {
    light: "https://svgl.app/library/sky.svg",
    dark: "https://svgl.app/library/sky.svg",
  },
  airbnb: {
    light: "https://svgl.app/library/airbnb.svg",
    dark: "https://svgl.app/library/airbnb.svg",
  },
  uber: {
    light: "https://svgl.app/library/uber_light.svg",
    dark: "https://svgl.app/library/uber_dark.svg",
  },
  gmail: {
    light: "https://svgl.app/library/gmail.svg",
    dark: "https://svgl.app/library/gmail.svg",
  },
  microsoftoutlook: {
    light: "https://svgl.app/library/microsoft-outlook.svg",
    dark: "https://svgl.app/library/microsoft-outlook.svg",
  },
  slack: {
    light: "https://svgl.app/library/slack.svg",
    dark: "https://svgl.app/library/slack.svg",
  },
  snapchat: {
    light: "https://svgl.app/library/snapchat.svg",
    dark: "https://svgl.app/library/snapchat.svg",
  },
  ebay: {
    light: "https://svgl.app/library/ebay.svg",
    dark: "https://svgl.app/library/ebay.svg",
  },
  ibm: {
    light: "https://svgl.app/library/ibm.svg",
    dark: "https://svgl.app/library/ibm.svg",
  },
  trustpilot: {
    light: "https://svgl.app/library/trustpilot.svg",
    dark: "https://svgl.app/library/trustpilot.svg",
  },
  raycast: {
    light: "https://svgl.app/library/raycast.svg",
    dark: "https://svgl.app/library/raycast.svg",
  },
  flowlauncher: {
    light: "https://svgl.app/library/FlowLauncher.svg",
    dark: "https://svgl.app/library/FlowLauncher.svg",
  },
  hackthebox: {
    light: "https://svgl.app/library/hack-the-box.svg",
    dark: "https://svgl.app/library/hack-the-box.svg",
  },
  procure: {
    light: "https://svgl.app/library/procure.svg",
    dark: "https://svgl.app/library/procure.svg",
  },
  julia: {
    light: "https://svgl.app/library/julia.svg",
    dark: "https://svgl.app/library/julia.svg",
  },
  swc: {
    light: "https://svgl.app/library/swc.svg",
    dark: "https://svgl.app/library/swc.svg",
  },
  playstation: {
    light: "https://svgl.app/library/playstation.svg",
    dark: "https://svgl.app/library/playstation.svg",
  },
  xbox: {
    light: "https://svgl.app/library/xbox.svg",
    dark: "https://svgl.app/library/xbox.svg",
  },
  cody: {
    light: "https://svgl.app/library/cody.svg",
    dark: "https://svgl.app/library/cody.svg",
  },
  sourcegraph: {
    light: "https://svgl.app/library/sourcegraph.svg",
    dark: "https://svgl.app/library/sourcegraph.svg",
  },
  perplexityai: {
    light: "https://svgl.app/library/perplexity.svg",
    dark: "https://svgl.app/library/perplexity.svg",
  },
  spring: {
    light: "https://svgl.app/library/spring.svg",
    dark: "https://svgl.app/library/spring.svg",
  },
  directus: {
    light: "https://svgl.app/library/directus.svg",
    dark: "https://svgl.app/library/directus.svg",
  },
  pnpm: {
    light: "https://svgl.app/library/pnpm.svg",
    dark: "https://svgl.app/library/pnpm_dark.svg",
  },
  emacs: {
    light: "https://svgl.app/library/emacs.svg",
    dark: "https://svgl.app/library/emacs.svg",
  },
  svgl: {
    light: "https://svgl.app/library/svgl.svg",
    dark: "https://svgl.app/library/svgl.svg",
  },
  googleidx: {
    light: "https://svgl.app/library/google-idx.svg",
    dark: "https://svgl.app/library/google-idx.svg",
  },
  remix: {
    light: "https://svgl.app/library/remix_light.svg",
    dark: "https://svgl.app/library/remix_dark.svg",
  },
  steam: {
    light: "https://svgl.app/library/steam.svg",
    dark: "https://svgl.app/library/steam.svg",
  },
  epicgames: {
    light: "https://svgl.app/library/epicgames-icon-light.svg",
    dark: "https://svgl.app/library/epicgames-icon-dark.svg",
  },
  tabby: {
    light: "https://svgl.app/library/tabby.svg",
    dark: "https://svgl.app/library/tabby.svg",
  },
  "1password": {
    light: "https://svgl.app/library/1password-light.svg",
    dark: "https://svgl.app/library/1password-dark.svg",
  },
  flask: {
    light: "https://svgl.app/library/flask-light.svg",
    dark: "https://svgl.app/library/flask-dark.svg",
  },
  alacritty: {
    light: "https://svgl.app/library/alacritty.svg",
    dark: "https://svgl.app/library/alacritty.svg",
  },
  qt: {
    light: "https://svgl.app/library/qt.svg",
    dark: "https://svgl.app/library/qt.svg",
  },
  bitwarden: {
    light: "https://svgl.app/library/bitwarden.svg",
    dark: "https://svgl.app/library/bitwarden.svg",
  },
  voicemod: {
    light: "https://svgl.app/library/voicemod_light.svg",
    dark: "https://svgl.app/library/voicemod_dark.svg",
  },
  neovim: {
    light: "https://svgl.app/library/neovim.svg",
    dark: "https://svgl.app/library/neovim.svg",
  },
  pitch: {
    light: "https://svgl.app/library/pitch.svg",
    dark: "https://svgl.app/library/pitch.svg",
  },
  biomejs: {
    light: "https://svgl.app/library/biomejs.svg",
    dark: "https://svgl.app/library/biomejs.svg",
  },
  gradio: {
    light: "https://svgl.app/library/gradio.svg",
    dark: "https://svgl.app/library/gradio.svg",
  },
  meta: {
    light: "https://svgl.app/library/meta.svg",
    dark: "https://svgl.app/library/meta.svg",
  },
  stabilityai: {
    light: "https://svgl.app/library/stability-ai.svg",
    dark: "https://svgl.app/library/stability-ai.svg",
  },
  googlepalm: {
    light: "https://svgl.app/library/google-palm.svg",
    dark: "https://svgl.app/library/google-palm.svg",
  },
  android: {
    light: "https://svgl.app/library/android-icon.svg",
    dark: "https://svgl.app/library/android-icon.svg",
  },
  sentry: {
    light: "https://svgl.app/library/sentry.svg",
    dark: "https://svgl.app/library/sentry.svg",
  },
  grafana: {
    light: "https://svgl.app/library/grafana.svg",
    dark: "https://svgl.app/library/grafana.svg",
  },
  notion: {
    light: "https://svgl.app/library/notion.svg",
    dark: "https://svgl.app/library/notion.svg",
  },
  litecoin: {
    light: "https://svgl.app/library/litecoin.svg",
    dark: "https://svgl.app/library/litecoin.svg",
  },
  elysiajs: {
    light: "https://svgl.app/library/elysiajs.svg",
    dark: "https://svgl.app/library/elysiajs.svg",
  },
  tensorflow: {
    light: "https://svgl.app/library/tensorflow-icon-light.svg",
    dark: "https://svgl.app/library/tensorflow-icon-dark.svg",
  },
  midday: {
    light: "https://svgl.app/library/midday.svg",
    dark: "https://svgl.app/library/midday.svg",
  },
  replicate: {
    light: "https://svgl.app/library/replicate_light.svg",
    dark: "https://svgl.app/library/replicate_dark.svg",
  },
  markdown: {
    light: "https://svgl.app/library/markdown-light.svg",
    dark: "https://svgl.app/library/markdown-dark.svg",
  },
  radixui: {
    light: "https://svgl.app/library/radix-ui_light.svg",
    dark: "https://svgl.app/library/radix-ui_dark.svg",
  },
  webdev: {
    light: "https://svgl.app/library/webdev.svg",
    dark: "https://svgl.app/library/webdev.svg",
  },
  swr: {
    light: "https://svgl.app/library/swr-light.svg",
    dark: "https://svgl.app/library/swr-dark.svg",
  },
  refine: {
    light: "https://svgl.app/library/refine_dark.svg",
    dark: "https://svgl.app/library/refine_light.svg",
  },
  youtubemusic: {
    light: "https://svgl.app/library/youtube_music.svg",
    dark: "https://svgl.app/library/youtube_music.svg",
  },
  tidal: {
    light: "https://svgl.app/library/tidal_light.svg",
    dark: "https://svgl.app/library/tidal_dark.svg",
  },
  obs: {
    light: "https://svgl.app/library/obs.svg",
    dark: "https://svgl.app/library/obs.svg",
  },
  stackoverflow: {
    light: "https://svgl.app/library/stackoverflow.svg",
    dark: "https://svgl.app/library/stackoverflow.svg",
  },
  tiktok: {
    light: "https://svgl.app/library/tiktok-icon-light.svg",
    dark: "https://svgl.app/library/tiktok-icon-dark.svg",
  },
  ngrok: {
    light: "https://svgl.app/library/ngrok-light.svg",
    dark: "https://svgl.app/library/ngrok-dark.svg",
  },
  lemonsqueezy: {
    light: "https://svgl.app/library/lemonsqueezy.svg",
    dark: "https://svgl.app/library/lemonsqueezy.svg",
  },
  asana: {
    light: "https://svgl.app/library/asana-logo.svg",
    dark: "https://svgl.app/library/asana-logo.svg",
  },
  upleveled: {
    light: "https://svgl.app/library/upleveled.svg",
    dark: "https://svgl.app/library/upleveled.svg",
  },
  zoom: {
    light: "https://svgl.app/library/zoom.svg",
    dark: "https://svgl.app/library/zoom.svg",
  },
  tina: {
    light: "https://svgl.app/library/tina.svg",
    dark: "https://svgl.app/library/tina.svg",
  },
  nextjs: {
    light: "https://svgl.app/library/nextjs_icon_dark.svg",
    dark: "https://svgl.app/library/nextjs_icon_dark.svg",
  },
  mistralai: {
    light: "https://svgl.app/library/mistral-ai_logo.svg",
    dark: "https://svgl.app/library/mistral-ai_logo.svg",
  },
  huggingface: {
    light: "https://svgl.app/library/hugging_face.svg",
    dark: "https://svgl.app/library/hugging_face.svg",
  },
  nodejs: {
    light: "https://svgl.app/library/nodejs.svg",
    dark: "https://svgl.app/library/nodejs.svg",
  },
  raindropio: {
    light: "https://svgl.app/library/raindrop.svg",
    dark: "https://svgl.app/library/raindrop.svg",
  },
  microsofttodo: {
    light: "https://svgl.app/library/microsoft-todo.svg",
    dark: "https://svgl.app/library/microsoft-todo.svg",
  },
  manifest: {
    light: "https://svgl.app/library/manifest.svg",
    dark: "https://svgl.app/library/manifest.svg",
  },
  supabase: {
    light: "https://svgl.app/library/supabase.svg",
    dark: "https://svgl.app/library/supabase.svg",
  },
  gleam: {
    light: "https://svgl.app/library/gleam.svg",
    dark: "https://svgl.app/library/gleam.svg",
  },
  flowbite: {
    light: "https://svgl.app/library/flowbite.svg",
    dark: "https://svgl.app/library/flowbite.svg",
  },
  humeai: {
    light: "https://svgl.app/library/hume-ai.svg",
    dark: "https://svgl.app/library/hume-ai.svg",
  },
  resend: {
    light: "https://svgl.app/library/resend-icon-black.svg",
    dark: "https://svgl.app/library/resend-icon-white.svg",
  },
  layers: {
    light: "https://svgl.app/library/layers_light.svg",
    dark: "https://svgl.app/library/layers_dark.svg",
  },
  exome: {
    light: "https://svgl.app/library/exome.svg",
    dark: "https://svgl.app/library/exome.svg",
  },
  poper: {
    light: "https://svgl.app/library/poper.svg",
    dark: "https://svgl.app/library/poper.svg",
  },
  dub: {
    light: "https://svgl.app/library/dub.svg",
    dark: "https://svgl.app/library/dub_dark_logo.svg",
  },
  turso: {
    light: "https://svgl.app/library/turso-light.svg",
    dark: "https://svgl.app/library/turso-dark.svg",
  },
  relagit: {
    light: "https://svgl.app/library/relagit-icon-light.svg",
    dark: "https://svgl.app/library/relagit-icon-dark.svg",
  },
  t3stack: {
    light: "https://svgl.app/library/t3-dark.svg",
    dark: "https://svgl.app/library/t3-light.svg",
  },
  applemusic: {
    light: "https://svgl.app/library/apple-music-icon.svg",
    dark: "https://svgl.app/library/apple-music-icon.svg",
  },
  acrobatscan: {
    light: "https://svgl.app/library/acrobat-scan.svg",
    dark: "https://svgl.app/library/acrobat-scan.svg",
  },
  adobesign: {
    light: "https://svgl.app/library/adobe-sign.svg",
    dark: "https://svgl.app/library/adobe-sign.svg",
  },
  adobeaero: {
    light: "https://svgl.app/library/aero.svg",
    dark: "https://svgl.app/library/aero.svg",
  },
  audition: {
    light: "https://svgl.app/library/audition.svg",
    dark: "https://svgl.app/library/audition.svg",
  },
  behance: {
    light: "https://svgl.app/library/behance.svg",
    dark: "https://svgl.app/library/behance.svg",
  },
  bridge: {
    light: "https://svgl.app/library/bridge.svg",
    dark: "https://svgl.app/library/bridge.svg",
  },
  captivate: {
    light: "https://svgl.app/library/captivate.svg",
    dark: "https://svgl.app/library/captivate.svg",
  },
  captivateprime: {
    light: "https://svgl.app/library/captivate-prime.svg",
    dark: "https://svgl.app/library/captivate-prime.svg",
  },
  capture: {
    light: "https://svgl.app/library/capture.svg",
    dark: "https://svgl.app/library/capture.svg",
  },
  characteranimator: {
    light: "https://svgl.app/library/character-animator.svg",
    dark: "https://svgl.app/library/character-animator.svg",
  },
  coldfusion: {
    light: "https://svgl.app/library/coldfusion.svg",
    dark: "https://svgl.app/library/coldfusion.svg",
  },
  coldfusionbuilder: {
    light: "https://svgl.app/library/coldfusion-builder.svg",
    dark: "https://svgl.app/library/coldfusion-builder.svg",
  },
  connect: {
    light: "https://svgl.app/library/connect.svg",
    dark: "https://svgl.app/library/connect.svg",
  },
  digitaleditions: {
    light: "https://svgl.app/library/digital-editions.svg",
    dark: "https://svgl.app/library/digital-editions.svg",
  },
  experienceplatform: {
    light: "https://svgl.app/library/experience-platform.svg",
    dark: "https://svgl.app/library/experience-platform.svg",
  },
  fillandsign: {
    light: "https://svgl.app/library/fill-and-sign.svg",
    dark: "https://svgl.app/library/fill-and-sign.svg",
  },
  fontfolio: {
    light: "https://svgl.app/library/fontfolio.svg",
    dark: "https://svgl.app/library/fontfolio.svg",
  },
  adobefonts: {
    light: "https://svgl.app/library/fonts.svg",
    dark: "https://svgl.app/library/fonts.svg",
  },
  framemaker: {
    light: "https://svgl.app/library/framemaker.svg",
    dark: "https://svgl.app/library/framemaker.svg",
  },
  framemakerserver: {
    light: "https://svgl.app/library/framemaker-server.svg",
    dark: "https://svgl.app/library/framemaker-server.svg",
  },
  fresco: {
    light: "https://svgl.app/library/fresco.svg",
    dark: "https://svgl.app/library/fresco.svg",
  },
  httpdynamicstreaming: {
    light: "https://svgl.app/library/http-dynamic-streaming.svg",
    dark: "https://svgl.app/library/http-dynamic-streaming.svg",
  },
  incopy: {
    light: "https://svgl.app/library/incopy.svg",
    dark: "https://svgl.app/library/incopy.svg",
  },
  indesignserver: {
    light: "https://svgl.app/library/indesign-server.svg",
    dark: "https://svgl.app/library/indesign-server.svg",
  },
  lightroomclassic: {
    light: "https://svgl.app/library/lightroom-classic.svg",
    dark: "https://svgl.app/library/lightroom-classic.svg",
  },
  mediaencoder: {
    light: "https://svgl.app/library/media-encoder.svg",
    dark: "https://svgl.app/library/media-encoder.svg",
  },
  mediaserver: {
    light: "https://svgl.app/library/media-server.svg",
    dark: "https://svgl.app/library/media-server.svg",
  },
  photoshopcamera: {
    light: "https://svgl.app/library/photoshop-camera.svg",
    dark: "https://svgl.app/library/photoshop-camera.svg",
  },
  photoshopelements: {
    light: "https://svgl.app/library/photoshop-elements.svg",
    dark: "https://svgl.app/library/photoshop-elements.svg",
  },
  photoshopexpress: {
    light: "https://svgl.app/library/photoshop-express.svg",
    dark: "https://svgl.app/library/photoshop-express.svg",
  },
  portfolio: {
    light: "https://svgl.app/library/portfolio.svg",
    dark: "https://svgl.app/library/portfolio.svg",
  },
  premiereelements: {
    light: "https://svgl.app/library/premiere-elements.svg",
    dark: "https://svgl.app/library/premiere-elements.svg",
  },
  premiererush: {
    light: "https://svgl.app/library/premiere-rush.svg",
    dark: "https://svgl.app/library/premiere-rush.svg",
  },
  presentervideoexpress: {
    light: "https://svgl.app/library/presenter-video-express.svg",
    dark: "https://svgl.app/library/presenter-video-express.svg",
  },
  robohelp: {
    light: "https://svgl.app/library/robohelp.svg",
    dark: "https://svgl.app/library/robohelp.svg",
  },
  robohelpserver: {
    light: "https://svgl.app/library/robohelp-server.svg",
    dark: "https://svgl.app/library/robohelp-server.svg",
  },
  adobestock: {
    light: "https://svgl.app/library/stock.svg",
    dark: "https://svgl.app/library/stock.svg",
  },
  substance3ddesigner: {
    light: "https://svgl.app/library/substance-3d-designer.svg",
    dark: "https://svgl.app/library/substance-3d-designer.svg",
  },
  substance3dpainter: {
    light: "https://svgl.app/library/substance-3d-painter.svg",
    dark: "https://svgl.app/library/substance-3d-painter.svg",
  },
  substance3dsampler: {
    light: "https://svgl.app/library/substance-3d-sampler.svg",
    dark: "https://svgl.app/library/substance-3d-sampler.svg",
  },
  substance3dstager: {
    light: "https://svgl.app/library/substance-3d-stager.svg",
    dark: "https://svgl.app/library/substance-3d-stager.svg",
  },
  technicalcommunicationsuite: {
    light: "https://svgl.app/library/technical-communication-suite.svg",
    dark: "https://svgl.app/library/technical-communication-suite.svg",
  },
  ygeeker: {
    light: "https://svgl.app/library/ygeeker.svg",
    dark: "https://svgl.app/library/ygeeker.svg",
  },
  postcss: {
    light: "https://svgl.app/library/postcss.svg",
    dark: "https://svgl.app/library/postcss.svg",
  },
  svg: {
    light: "https://svgl.app/library/svg.svg",
    dark: "https://svgl.app/library/svg.svg",
  },
  pdf: {
    light: "https://svgl.app/library/pdf.svg",
    dark: "https://svgl.app/library/pdf.svg",
  },
  todoist: {
    light: "https://svgl.app/library/todoist.svg",
    dark: "https://svgl.app/library/todoist.svg",
  },
  apidog: {
    light: "https://svgl.app/library/apidog.svg",
    dark: "https://svgl.app/library/apidog.svg",
  },
  chartjs: {
    light: "https://svgl.app/library/chartjs.svg",
    dark: "https://svgl.app/library/chartjs.svg",
  },
  jsonschema: {
    light: "https://svgl.app/library/json-schema.svg",
    dark: "https://svgl.app/library/json-schema.svg",
  },
  eve: {
    light: "https://svgl.app/library/eve-light.svg",
    dark: "https://svgl.app/library/eve-dark.svg",
  },
  v0: {
    light: "https://svgl.app/library/v0_light.svg",
    dark: "https://svgl.app/library/v0_dark.svg",
  },
  bento: {
    light: "https://svgl.app/library/bento.svg",
    dark: "https://svgl.app/library/bento.svg",
  },
  firebase: {
    light: "https://svgl.app/library/firebase.svg",
    dark: "https://svgl.app/library/firebase.svg",
  },
  prettier: {
    light: "https://svgl.app/library/prettier-icon-light.svg",
    dark: "https://svgl.app/library/prettier-icon-dark.svg",
  },
  leapwallet: {
    light: "https://svgl.app/library/leap-wallet.svg",
    dark: "https://svgl.app/library/leap-wallet.svg",
  },
  nx: {
    light: "https://svgl.app/library/nx_light.svg",
    dark: "https://svgl.app/library/nx_dark.svg",
  },
  googlecolaboratory: {
    light: "https://svgl.app/library/Google_Colaboratory.svg",
    dark: "https://svgl.app/library/Google_Colaboratory.svg",
  },
  raspberrypi: {
    light: "https://svgl.app/library/raspberry_pi.svg",
    dark: "https://svgl.app/library/raspberry_pi.svg",
  },
  manzdev: {
    light: "https://svgl.app/library/manzdev.svg",
    dark: "https://svgl.app/library/manzdev.svg",
  },
  mediawiki: {
    light: "https://svgl.app/library/mediawiki.svg",
    dark: "https://svgl.app/library/mediawiki.svg",
  },
  carrd: {
    light: "https://svgl.app/library/carrd.svg",
    dark: "https://svgl.app/library/carrd.svg",
  },
  claudeai: {
    light: "https://svgl.app/library/claude-ai-icon.svg",
    dark: "https://svgl.app/library/claude-ai-icon.svg",
  },
  unocss: {
    light: "https://svgl.app/library/unocss.svg",
    dark: "https://svgl.app/library/unocss.svg",
  },
  trpc: {
    light: "https://svgl.app/library/trpc.svg",
    dark: "https://svgl.app/library/trpc.svg",
  },
  bluesky: {
    light: "https://svgl.app/library/bluesky.svg",
    dark: "https://svgl.app/library/bluesky.svg",
  },
  drizzleorm: {
    light: "https://svgl.app/library/drizzle-orm_light.svg",
    dark: "https://svgl.app/library/drizzle-orm_dark.svg",
  },
  dailydev: {
    light: "https://svgl.app/library/daily-dev-ligth.svg",
    dark: "https://svgl.app/library/daily-dev-dark.svg",
  },
  polars: {
    light: "https://svgl.app/library/polars-logo.svg",
    dark: "https://svgl.app/library/polars-logo.svg",
  },
  zed: {
    light: "https://svgl.app/library/zed-logo.svg",
    dark: "https://svgl.app/library/zed-logo_dark.svg",
  },
  polar: {
    light: "https://svgl.app/library/polar-sh_light.svg",
    dark: "https://svgl.app/library/polar-sh_dark.svg",
  },
  bolt: {
    light: "https://svgl.app/library/bolt-new.svg",
    dark: "https://svgl.app/library/bolt-new_dark.svg",
  },
  json: {
    light: "https://svgl.app/library/json.svg",
    dark: "https://svgl.app/library/json.svg",
  },
  nuqs: {
    light: "https://svgl.app/library/nuqs.svg",
    dark: "https://svgl.app/library/nuqs_dark.svg",
  },
  soundcloud: {
    light: "https://svgl.app/library/soundcloud-logo.svg",
    dark: "https://svgl.app/library/soundcloud-logo_dark.svg",
  },
  mermaid: {
    light: "https://svgl.app/library/mermaid-logo-light.svg",
    dark: "https://svgl.app/library/mermaid-logo-dark.svg",
  },
  homeassistant: {
    light: "https://svgl.app/library/home-assistant.svg",
    dark: "https://svgl.app/library/home-assistant.svg",
  },
  uxanarangel: {
    light: "https://svgl.app/library/uxanarangel-light.svg",
    dark: "https://svgl.app/library/uxanarangel-dark.svg",
  },
  uxcorprangel: {
    light: "https://svgl.app/library/uxcorprangel-light.svg",
    dark: "https://svgl.app/library/uxcorprangel-dark.svg",
  },
  posthog: {
    light: "https://svgl.app/library/posthog.svg",
    dark: "https://svgl.app/library/posthog.svg",
  },
  powertoys: {
    light: "https://svgl.app/library/powertoys.svg",
    dark: "https://svgl.app/library/powertoys.svg",
  },
  powershell: {
    light: "https://svgl.app/library/powershell.svg",
    dark: "https://svgl.app/library/powershell.svg",
  },
  lottielab: {
    light: "https://svgl.app/library/lottielab.svg",
    dark: "https://svgl.app/library/lottielab.svg",
  },
  typegpu: {
    light: "https://svgl.app/library/typegpu-light.svg",
    dark: "https://svgl.app/library/typegpu-dark.svg",
  },
  microsoftnet: {
    light: "https://svgl.app/library/dotnet.svg",
    dark: "https://svgl.app/library/dotnet.svg",
  },
  dotenv: {
    light: "https://svgl.app/library/dotenv.svg",
    dark: "https://svgl.app/library/dotenv.svg",
  },
  dotenvx: {
    light: "https://svgl.app/library/dotenvx.svg",
    dark: "https://svgl.app/library/dotenvx.svg",
  },
  motion: {
    light: "https://svgl.app/library/motion.svg",
    dark: "https://svgl.app/library/motion_dark.svg",
  },
  keycloak: {
    light: "https://svgl.app/library/keycloak.svg",
    dark: "https://svgl.app/library/keycloak.svg",
  },
  deepseek: {
    light: "https://svgl.app/library/deepseek.svg",
    dark: "https://svgl.app/library/deepseek.svg",
  },
  shiki: {
    light: "https://svgl.app/library/shiki.svg",
    dark: "https://svgl.app/library/shiki.svg",
  },
  dropbox: {
    light: "https://svgl.app/library/dropbox.svg",
    dark: "https://svgl.app/library/dropbox.svg",
  },
  openwebui: {
    light: "https://svgl.app/library/openwebui.svg",
    dark: "https://svgl.app/library/openwebui.svg",
  },
  baseui: {
    light: "https://svgl.app/library/base-ui.svg",
    dark: "https://svgl.app/library/base-ui-dark.svg",
  },
  vercel: {
    light: "https://svgl.app/library/vercel.svg",
    dark: "https://svgl.app/library/vercel_dark.svg",
  },
  modelcontextprotocol: {
    light: "https://svgl.app/library/model-context-protocol-light.svg",
    dark: "https://svgl.app/library/model-context-protocol-dark.svg",
  },
  socketio: {
    light: "https://svgl.app/library/socketio-icon-light.svg",
    dark: "https://svgl.app/library/socketio-icon-dark.svg",
  },
  antdesign: {
    light: "https://svgl.app/library/ant-design-dark-theme.svg",
    dark: "https://svgl.app/library/ant-design-dark-theme.svg",
  },
  vscodium: {
    light: "https://svgl.app/library/vscodium.svg",
    dark: "https://svgl.app/library/vscodium.svg",
  },
  zenbrowser: {
    light: "https://svgl.app/library/zen-browser-light.svg",
    dark: "https://svgl.app/library/zen-browser-dark.svg",
  },
  gemini: {
    light: "https://svgl.app/library/gemini.svg",
    dark: "https://svgl.app/library/gemini.svg",
  },
  xai: {
    light: "https://svgl.app/library/xai_light.svg",
    dark: "https://svgl.app/library/xai_dark.svg",
  },
  qwen: {
    light: "https://svgl.app/library/qwen_light.svg",
    dark: "https://svgl.app/library/qwen_dark.svg",
  },
  inflectionai: {
    light: "https://svgl.app/library/inflectionai_light.svg",
    dark: "https://svgl.app/library/inflectionai_dark.svg",
  },
  d3js: {
    light: "https://svgl.app/library/D3.svg",
    dark: "https://svgl.app/library/D3.svg",
  },
  anthropic: {
    light: "https://svgl.app/library/anthropic_black.svg",
    dark: "https://svgl.app/library/anthropic_white.svg",
  },
  replit: {
    light: "https://svgl.app/library/replit.svg",
    dark: "https://svgl.app/library/replit.svg",
  },
  magicui: {
    light: "https://svgl.app/library/magicui.svg",
    dark: "https://svgl.app/library/magicui.svg",
  },
  webcomponents: {
    light: "https://svgl.app/library/webcomponents.svg",
    dark: "https://svgl.app/library/webcomponents.svg",
  },
  designali: {
    light: "https://svgl.app/library/designali.svg",
    dark: "https://svgl.app/library/designali.svg",
  },
  curseforge: {
    light: "https://svgl.app/library/curseforge.svg",
    dark: "https://svgl.app/library/curseforge-dark.svg",
  },
  ghostty: {
    light: "https://svgl.app/library/ghostty.svg",
    dark: "https://svgl.app/library/ghostty.svg",
  },
  betterauth: {
    light: "https://svgl.app/library/better-auth_light.svg",
    dark: "https://svgl.app/library/better-auth_dark.svg",
  },
  buymeacoffee: {
    light: "https://svgl.app/library/bmc.svg",
    dark: "https://svgl.app/library/bmc.svg",
  },
  github: {
    light: "https://svgl.app/library/github_light.svg",
    dark: "https://svgl.app/library/github_dark.svg",
  },
  firebasestudio: {
    light: "https://svgl.app/library/firebase-studio.svg",
    dark: "https://svgl.app/library/firebase-studio.svg",
  },
  dingocoin: {
    light: "https://svgl.app/library/dingocoin.svg",
    dark: "https://svgl.app/library/dingocoin.svg",
  },
  heroui: {
    light: "https://svgl.app/library/heroui_black.svg",
    dark: "https://svgl.app/library/heroui_light.svg",
  },
  convex: {
    light: "https://svgl.app/library/convex.svg",
    dark: "https://svgl.app/library/convex.svg",
  },
  clerk: {
    light: "https://svgl.app/library/clerk-icon-light.svg",
    dark: "https://svgl.app/library/clerk-icon-dark.svg",
  },
  terraform: {
    light: "https://svgl.app/library/terraform.svg",
    dark: "https://svgl.app/library/terraform.svg",
  },
  rspack: {
    light: "https://svgl.app/library/rspack.svg",
    dark: "https://svgl.app/library/rspack.svg",
  },
  rsbuild: {
    light: "https://svgl.app/library/rsbuild.svg",
    dark: "https://svgl.app/library/rsbuild.svg",
  },
  reactwheelpicker: {
    light: "https://svgl.app/library/react-wheel-picker_light.svg",
    dark: "https://svgl.app/library/react-wheel-picker_dark.svg",
  },
  cpanel: {
    light: "https://svgl.app/library/cP_orange.svg",
    dark: "https://svgl.app/library/cP_orange.svg",
  },
  lovable: {
    light: "https://svgl.app/library/lovable.svg",
    dark: "https://svgl.app/library/lovable.svg",
  },
  mocha: {
    light: "https://svgl.app/library/mocha-light.svg",
    dark: "https://svgl.app/library/mocha-dark.svg",
  },
  openrouter: {
    light: "https://svgl.app/library/openrouter_light.svg",
    dark: "https://svgl.app/library/openrouter_dark.svg",
  },
  openhunts: {
    light: "https://svgl.app/library/openhunts.svg",
    dark: "https://svgl.app/library/openhunts.svg",
  },
  kokonutui: {
    light: "https://svgl.app/library/kokonutui-light.svg",
    dark: "https://svgl.app/library/kokonutui-dark.svg",
  },
  googlecloud: {
    light: "https://svgl.app/library/google-cloud.svg",
    dark: "https://svgl.app/library/google-cloud.svg",
  },
  zulip: {
    light: "https://svgl.app/library/zulip.svg",
    dark: "https://svgl.app/library/zulip.svg",
  },
  effectts: {
    light: "https://svgl.app/library/effect_light.svg",
    dark: "https://svgl.app/library/effect_dark.svg",
  },
  arkui: {
    light: "https://svgl.app/library/ark-ui.svg",
    dark: "https://svgl.app/library/ark-ui.svg",
  },
  mantine: {
    light: "https://svgl.app/library/mantine.svg",
    dark: "https://svgl.app/library/mantine.svg",
  },
  eslint: {
    light: "https://svgl.app/library/eslint-icon-light.svg",
    dark: "https://svgl.app/library/eslint-icon-dark.svg",
  },
  apachekafka: {
    light: "https://svgl.app/library/apache-kafka-light.svg",
    dark: "https://svgl.app/library/apache-kafka-dark.svg",
  },
  plainsignal: {
    light: "https://svgl.app/library/plainsignal.svg",
    dark: "https://svgl.app/library/plainsignal.svg",
  },
  heptabase: {
    light: "https://svgl.app/library/heptabase.svg",
    dark: "https://svgl.app/library/heptabase.svg",
  },
  unjs: {
    light: "https://svgl.app/library/unjs.svg",
    dark: "https://svgl.app/library/unjs.svg",
  },
  powersync: {
    light: "https://svgl.app/library/powersync.svg",
    dark: "https://svgl.app/library/powersync.svg",
  },
  n8n: {
    light: "https://svgl.app/library/n8n.svg",
    dark: "https://svgl.app/library/n8n.svg",
  },
  kiboui: {
    light: "https://svgl.app/library/kibo-ui-light.svg",
    dark: "https://svgl.app/library/kibo-ui-dark.svg",
  },
  ahrefs: {
    light: "https://svgl.app/library/ahrefs.svg",
    dark: "https://svgl.app/library/ahrefs.svg",
  },
  googlemaps: {
    light: "https://svgl.app/library/googleMaps.svg",
    dark: "https://svgl.app/library/googleMaps.svg",
  },
  webgl: {
    light: "https://svgl.app/library/webgl.svg",
    dark: "https://svgl.app/library/webgl_dark.svg",
  },
  intello: {
    light: "https://svgl.app/library/intello-dark.svg",
    dark: "https://svgl.app/library/intello-light.svg",
  },
  kilocode: {
    light: "https://svgl.app/library/kilocode-light.svg",
    dark: "https://svgl.app/library/kilocode-dark.svg",
  },
  cursor: {
    light: "https://svgl.app/library/cursor_light.svg",
    dark: "https://svgl.app/library/cursor_dark.svg",
  },
  lottiefiles: {
    light: "https://svgl.app/library/lottiefiles.svg",
    dark: "https://svgl.app/library/lottiefiles.svg",
  },
  mintlify: {
    light: "https://svgl.app/library/mintlify.svg",
    dark: "https://svgl.app/library/mintlify.svg",
  },
  qdrant: {
    light: "https://svgl.app/library/qdrant-icon-light.svg",
    dark: "https://svgl.app/library/qdrant-icon-dark.svg",
  },
  travelperk: {
    light: "https://svgl.app/library/travelperk-light.svg",
    dark: "https://svgl.app/library/travelperk-dark.svg",
  },
  sanity: {
    light: "https://svgl.app/library/sanity-light.svg",
    dark: "https://svgl.app/library/sanity-dark.svg",
  },
  nginx: {
    light: "https://svgl.app/library/nginx.svg",
    dark: "https://svgl.app/library/nginx.svg",
  },
  soldera: {
    light: "https://svgl.app/library/soldera-icon-light.svg",
    dark: "https://svgl.app/library/soldera-icon.svg",
  },
  dribbble: {
    light: "https://svgl.app/library/dribbble.svg",
    dark: "https://svgl.app/library/dribbble.svg",
  },
  paper: {
    light: "https://svgl.app/library/paper.svg",
    dark: "https://svgl.app/library/paper.svg",
  },
  dodopayments: {
    light: "https://svgl.app/library/dodo-payments.svg",
    dark: "https://svgl.app/library/dodo-payments.svg",
  },
  formance: {
    light: "https://svgl.app/library/formance-light.svg",
    dark: "https://svgl.app/library/formance-dark.svg",
  },
  bklit: {
    light: "https://svgl.app/library/bklit-light.svg",
    dark: "https://svgl.app/library/bklit-dark.svg",
  },
  intlayer: {
    light: "https://svgl.app/library/intlayer-light.svg",
    dark: "https://svgl.app/library/intlayer-dark.svg",
  },
  goil: {
    light: "https://svgl.app/library/goil.svg",
    dark: "https://svgl.app/library/goil-dark.svg",
  },
  vite: {
    light: "https://svgl.app/library/vite.svg",
    dark: "https://svgl.app/library/vite.svg",
  },
  vitest: {
    light: "https://svgl.app/library/vitest.svg",
    dark: "https://svgl.app/library/vitest.svg",
  },
  oxc: {
    light: "https://svgl.app/library/oxc.svg",
    dark: "https://svgl.app/library/oxc.svg",
  },
  rolldown: {
    light: "https://svgl.app/library/rolldown.svg",
    dark: "https://svgl.app/library/rolldown.svg",
  },
  voidzero: {
    light: "https://svgl.app/library/voidzero.svg",
    dark: "https://svgl.app/library/voidzero.svg",
  },
  tembo: {
    light: "https://svgl.app/library/tembo.svg",
    dark: "https://svgl.app/library/tembo-dark.svg",
  },
  firecrawl: {
    light: "https://svgl.app/library/firecrawl.svg",
    dark: "https://svgl.app/library/firecrawl-dark.svg",
  },
  abacatepay: {
    light: "https://svgl.app/library/abacatepay.svg",
    dark: "https://svgl.app/library/abacatepay.svg",
  },
  googlecalendar: {
    light: "https://svgl.app/library/google-calendar.svg",
    dark: "https://svgl.app/library/google-calendar.svg",
  },
  googlemeet: {
    light: "https://svgl.app/library/google-meet.svg",
    dark: "https://svgl.app/library/google-meet.svg",
  },
  googlesheets: {
    light: "https://svgl.app/library/google-sheets.svg",
    dark: "https://svgl.app/library/google-sheets.svg",
  },
  googleslides: {
    light: "https://svgl.app/library/google-slides.svg",
    dark: "https://svgl.app/library/google-slides.svg",
  },
  googlechat: {
    light: "https://svgl.app/library/google-chat.svg",
    dark: "https://svgl.app/library/google-chat.svg",
  },
  googleanalytics: {
    light: "https://svgl.app/library/google-analytics.svg",
    dark: "https://svgl.app/library/google-analytics.svg",
  },
  hotmart: {
    light: "https://svgl.app/library/hotmart.svg",
    dark: "https://svgl.app/library/hotmart.svg",
  },
  microsoftoffice: {
    light: "https://svgl.app/library/microsoft-office.svg",
    dark: "https://svgl.app/library/microsoft-office.svg",
  },
  midjourney: {
    light: "https://svgl.app/library/midjourney.svg",
    dark: "https://svgl.app/library/midjourney-dark.svg",
  },
  manus: {
    light: "https://svgl.app/library/manus.svg",
    dark: "https://svgl.app/library/manus-dark.svg",
  },
  glide: {
    light: "https://svgl.app/library/glide_light.svg",
    dark: "https://svgl.app/library/glide_dark.svg",
  },
  vlt: {
    light: "https://svgl.app/library/vlt-light.svg",
    dark: "https://svgl.app/library/vlt-dark.svg",
  },
  opencode: {
    light: "https://svgl.app/library/opencode.svg",
    dark: "https://svgl.app/library/opencode-dark.svg",
  },
  openclaw: {
    light: "https://svgl.app/library/openclaw.svg",
    dark: "https://svgl.app/library/openclaw.svg",
  },
  dracula: {
    light: "https://svgl.app/library/dracula-dark.svg",
    dark: "https://svgl.app/library/dracula.svg",
  },
  render: {
    light: "https://svgl.app/library/render_black.svg",
    dark: "https://svgl.app/library/render_white.svg",
  },
  xata: {
    light: "https://svgl.app/library/xata.svg",
    dark: "https://svgl.app/library/xata.svg",
  },
  stripe: {
    light: "https://svgl.app/library/stripe.svg",
    dark: "https://svgl.app/library/stripe.svg",
  },
  interfere: {
    light: "https://svgl.app/library/interfere_black.svg",
    dark: "https://svgl.app/library/interfere_white.svg",
  },
  orshot: {
    light: "https://svgl.app/library/orshot.svg",
    dark: "https://svgl.app/library/orshot.svg",
  },
  codex: {
    light: "https://svgl.app/library/codex_light.svg",
    dark: "https://svgl.app/library/codex_dark.svg",
  },
  conductor: {
    light: "https://svgl.app/library/conductor_light.svg",
    dark: "https://svgl.app/library/conductor_dark.svg",
  },
  leedlime: {
    light: "https://svgl.app/library/leedlime.svg",
    dark: "https://svgl.app/library/leedlime.svg",
  },
  cerebras: {
    light: "https://svgl.app/library/cerebras-dark.svg",
    dark: "https://svgl.app/library/cerebras.svg",
  },
  runframe: {
    light: "https://svgl.app/library/runframe.svg",
    dark: "https://svgl.app/library/runframe.svg",
  },
  acrobatreader: {
    light: "https://svgl.app/library/reader_appicon_64_grayscale.svg",
    dark: "https://svgl.app/library/reader_appicon_64_grayscale.svg",
  },
  nano: {
    light: "https://svgl.app/library/nano.svg",
    dark: "https://svgl.app/library/nano-white.svg",
  },
  photopea: {
    light: "https://svgl.app/library/photopea.svg",
    dark: "https://svgl.app/library/photopea.svg",
  },
  trello: {
    light: "https://svgl.app/library/trello.svg",
    dark: "https://svgl.app/library/trello.svg",
  },
  clickup: {
    light: "https://svgl.app/library/clickup.svg",
    dark: "https://svgl.app/library/clickup.svg",
  },
  postqued: {
    light: "https://svgl.app/library/postqued-light.svg",
    dark: "https://svgl.app/library/postqued-dark.svg",
  },
  grida: {
    light: "https://svgl.app/library/grida-light.svg",
    dark: "https://svgl.app/library/grida-dark.svg",
  },
  depot: {
    light: "https://svgl.app/library/depot-light.svg",
    dark: "https://svgl.app/library/depot-dark.svg",
  },
  tanstack: {
    light: "https://svgl.app/library/tanstack_light.svg",
    dark: "https://svgl.app/library/tanstack_dark.svg",
  },
  mastra: {
    light: "https://svgl.app/library/mastra-icon-light.svg",
    dark: "https://svgl.app/library/mastra-icon-dark.svg",
  },
  retain: {
    light: "https://svgl.app/library/retain-light.svg",
    dark: "https://svgl.app/library/retain-dark.svg",
  },
  typesafeai: {
    light: "https://svgl.app/library/typesafe-ai-light.svg",
    dark: "https://svgl.app/library/typesafe-ai-dark.svg",
  },
};
